### ISSUE TITLE
problems syncing: TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by pisaniej** [bb-Ricardo/netbox-sync#104]
When trying to sync for the first time, I'm encountering the below:
```
2021-10-15 10:40:22,751 - INFO: Updating changed data in NetBox
2021-10-15 10:40:22,801 - INFO: Creating new NetBox 'tag' object 'NetBox-synced: Orphaned' with data: {'name': 'NetBox-synced: Orphaned', 'color': '607d8b', 'description': 'A source which has previously provided this object no longer states it exists. Objects would be automatically removed after 30 days but pruning is currently disabled.', 'slug': 'netbox-synced-orphaned'}
2021-10-15 10:40:22,941 - INFO: Creating new NetBox 'tag' object 'NetBox-synced' with data: {'name': 'NetBox-synced', 'description': "Created and used by NetBox Sync Script to keep track of created items. DO NOT change this tag, otherwise syncing can't keep track of deleted objects.", 'slug': 'netbox-synced'}
2021-10-15 10:40:23,017 - INFO: Creating new NetBox 'tag' object 'Source: our-vcenter' with data: {'name': 'Source: our-vcenter', 'description': 'Marks sources synced from vCenter our-vcenter (vcenterhostname) to this NetBox Instance.', 'slug': 'source-our-vcenter'}
2021-10-15 10:40:23,053 - INFO: Creating new NetBox 'site' object 'vCenter: our-vcenter' with data: {'name': 'vCenter: our-vcenter', 'slug': 'vcenter-our-vcenter', 'comments': 'A default virtual site created to house objects that have been synced from this vCenter instance and have no predefined site assigned.'}
2021-10-15 10:40:23,191 - INFO: Found unset key 'name' while parsing None. Skipping This key
2021-10-15 10:40:23,191 - INFO: Found unset key 'name' while parsing None. Skipping This key
Traceback (most recent call last):
  File "./netbox-sync.py", line 143, in <module>
    main()
  File "./netbox-sync.py", line 133, in main
    nb_handler.update_instance()
  File "/opt/netbox-sync/module/netbox/connection.py", line 705, in update_instance
    self.update_object(nb_object_sub_class)
  File "/opt/netbox-sync/module/netbox/connection.py", line 675, in update_object
    this_object.update(data=unresolved_dependency_data)
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 369, in update
    new_value_str = str(new_value.get_display_name())
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 762, in get_display_name
    return sorted([x.get_display_name() for x in self])
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by pisaniej** [comment]
hi @bb-Ricardo apologies for the delay. Is the fix still available for testing?

**Comment by bb-Ricardo** [comment]
Hi, This one is merged to 'main' branch since a while. just get the latest release and it should be fixed

**Comment by pisaniej** [comment]
@bb-Ricardo ah okay. I'm still receiving a similar primary key error and thought it was related

```
2022-02-01 14:00:04,018 - INFO: Creating new NetBox 'IP address' object '10.254.125.16/24' with data: {'address': '10.254.125.16/24', 'assigned_object_type': 'virtualization.vminterface', 'dns_name': 'server1.example.com'}
2022-02-01 14:00:04,018 - DEBUG2: Sending POST to 'http://netbox.example.com:80/api/ipam/ip-addresses/' with data 'b'{"address": "10.254.125.16/24", "assigned_object_type": "virtualization.vminterface", "dns_name": "server1.example.com"}''.
2022-02-01 14:00:04,057 - DEBUG2: Received HTTP Status 200.
2022-02-01 14:00:04,057 - ERROR: This 'IP address' data structure does not contain the primary key 'address' got: {'count': 0, 'next': None, 'previous': None, 'results': []}
2022-02-01 14:00:04,058 - DEBUG2: Adding unresolved dependencies back to object: ['tags', 'assigned_object_id']
2022-02-01 14:00:04,058 - DEBUG2: Parsing 'IP address' data structure: 10.254.125.16/24
```

**Comment by bb-Ricardo** [comment]
Ui, the problem still seems to persists as it looks like.

For some reason Netbox does not return the created object. Not sure where the issue exists.

Can you try `-l DEBUG3`. This will print out A LOT of data. Try to find the exact lines lines as in your last post. There you should see the original NetBox answer.

**Comment by pisaniej** [comment]
@bb-Ricardo working on it, will report back.

I should also notice that I'm attempting to import this into a completely new/empty netbox instance. My config is as follows:

```
[common]
[netbox]
api_token = secret
host_fqdn = netbox.example.com
port = 80
disable_tls = true
validate_tls_certs = false
prune_enabled = false

[source/my-vcenter-example]
type = vmware
host_fqdn = vcenter.example.com
username = user
password = pass
permitted_subnets = 172.16.0.0/12, 10.0.0.0/8, 192.168.0.0/16, fd00::/8
dns_name_lookup = True

**Comment by bb-Ricardo** [comment]
This looks fine to me.

I also use for testing an empty NetBox and fill it with data from a copied vCenter instance.

**Comment by pisaniej** [comment]
@bb-Ricardo here is the output. I scrubbed it up a bit:

```
send: b'POST /sdk HTTP/1.1\r\nHost: vcenter.example.com\r\nContent-Length: 675\r\nCookie: vmware_soap_session="xxxxx"; Path=/; HttpOnly; Secure;\r\nSOAPAction: "urn:vim25/6.7.3"\r\nContent-Type: text/xml; charset=UTF-8\r\nUser-Agent: pyvmomi Python/3.8.8 (Linux; 4.18.0-348.7.1.el8_5.x86_64; x86_64)\r\nAccept-Encoding: gzip, deflate\r\n\r\n'
send: b'<?xml version="1.0" encoding="UTF-8"?>\n<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">\n<soapenv:Body><RetrievePropertiesEx xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this><specSet><propSet><type>VirtualMachine</type><all>false</all><pathSet>guest</pathSet></propSet><objectSet><obj type="VirtualMachine">vm-581785</obj><skip>false</skip></objectSet></specSet><options><maxObjects>1</maxObjects></options></RetrievePropertiesEx></soapenv:Body>\n</soapenv:Envelope>'
reply: 'HTTP/1.1 200 OK\r\n'
header: date: Tue, 1 Feb 2022 19:28:59 GMT
header: cache-control: no-cache
header: content-type: text/xml; charset=utf-8
header: content-length: 3618
header: x-envoy-upstream-service-time: 1
header: server: envoy
{'cluster': {'name': 'example_cluster'},
 'disk': 100,
 'memory': 8192,
 'name': 'server1',
 'platform': {'name': 'Red Hat Enterprise Linux 7 (64-bit)'},
 'status': 'active',
 'vcpus': 4}
None
{'vNIC 1 (intprod - 0.0.0.0%2f24 (1352))': {'description': 'Network '
                                                                            'adapter '
                                                                            '1 '
                                                                            '(VV3) '
                                                                            '(vlan '
                                                                            'ID: '
                                                                            '1352)',
                                                             'enabled': True,
                                                             'mac_address': 'FF:FF:FF:FF:FF:FF',
                                                             'mode': 'access',
                                                             'mtu': 1500,
                                                             'name': 'vNIC 1 '
                                                                     '(intprod
                                                                     '- '
                                                                     '0.0.0.0/24 '
                                                                     '(1352))',
                                                             'untagged_vlan': {'name': 'intprod '
                                                                                       '- '
                                                                                       '0.0.0.0/24 '2022-02-01 14:28:59,563 - DEBUG2: Trying to find a virtual machine based on the collected name, cluster, IP and MAC addresses
2022-02-01 14:28:59,604 - DEBUG2: No exact match found. Trying to find virtual machine based on MAC addresses
2022-02-01 14:28:59,608 - DEBUG2: No match found. Trying to find virtual machine based on primary IP addresses
2022-02-01 14:28:59,608 - DEBUG: No existing virtual machine object for server1. Creating a new virtual machine.
2022-02-01 14:28:59,608 - DEBUG2: Parsing 'virtual machine' data structure: server1
2022-02-01 14:28:59,608 - DEBUG2: Parsing 'cluster' data structure: example_cluster
2022-02-01 14:28:59,609 - DEBUG2: Parsing 'platform' data structure: Red Hat Enterprise Linux 7 (64-bit)
2022-02-01 14:28:59,609 - INFO: Created new virtual machine object: server1
2022-02-01 14:28:59,609 - DEBUG2: Parsing 'virtual machine' data structure: server1
2022-02-01 14:28:59,609 - DEBUG2: Parsing 'device role' data structure: Server
2022-02-01 14:28:59,609 - DEBUG2: Trying to match current object interfaces in NetBox with discovered interfaces
2022-02-01 14:28:59,612 - DEBUG2: Found '0' NICs in NetBox for 'server1'
2022-02-01 14:28:59,612 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (intprod - 140.160.78.0/24 (1352)) (server1)
2022-02-01 14:28:59,612 - INFO: Created new virtual machine interface object: vNIC 1 (intprod - 0.0.0.0/24 (1352)) (server1)
2022-02-01 14:28:59,612 - DEBUG2: Trying to find a VLAN based on the VLAN id '1352'
2022-02-01 14:28:59,613 - DEBUG2: Found a exact matching VLAN object: 1352 (vCenter: my-vcenter-example)
2022-02-01 14:28:59,613 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (intprod - 0.0.0.0/24 (1352)) (server1)

                                                                                       '(1352)',
                                                                               'site': {'name': 'vCenter: '
                                                                                                'my-vcenter-example'},
                                                                               'vid': 1352},
                                                             'virtual_machine': None}}
{'vNIC 1 (intprod - 0.0.0.0%2f24 (1352))': []}
None
None
obj.AcquireMksTicket = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.AcquireTicket = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Answer = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.AnswerVM = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ApplyEvcMode = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ApplyEvcModeVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Array = <class 'pyVmomi.VmomiSupport.vim.VirtualMachine[]'>
obj.AttachDisk = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.AttachDisk_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CheckCustomizationSpec = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Clone = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CloneVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ConsolidateDisks = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ConsolidateVMDisks_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateScreenshot = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateScreenshot_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSecondary = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSecondaryEx = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSecondaryVMEx_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSecondaryVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSnapshot = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSnapshotEx = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSnapshotEx_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CreateSnapshot_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CryptoUnlock = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CryptoUnlock_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Customize = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.CustomizeVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.DefragmentAllDisks = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Destroy = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Destroy_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.DetachDisk = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.DetachDisk_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.DisableSecondary = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.DisableSecondaryVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.EnableSecondary = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.EnableSecondaryVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.EstimateStorageForConsolidateSnapshots_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.EstimateStorageRequirementForConsolidate = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ExportVm = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ExtractOvfEnvironment = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.InstantClone = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.InstantClone_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MakePrimary = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MakePrimaryVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MarkAsTemplate = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MarkAsVirtualMachine = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Migrate = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MigrateVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.MountToolsInstaller = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PowerOff = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PowerOffVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PowerOn = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PowerOnVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PromoteDisks = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PromoteDisks_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.PutUsbScanCodes = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.QueryChangedDiskAreas = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.QueryFaultToleranceCompatibility = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.QueryFaultToleranceCompatibilityEx = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.QueryUnownedFiles = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RebootGuest = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ReconfigVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Reconfigure = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RefreshStorageInfo = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Reload = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ReloadFromPath = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Relocate = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RelocateVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RemoveAllSnapshots = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RemoveAllSnapshots_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Rename = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Rename_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Reset = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ResetGuestInformation = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ResetVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RevertToCurrentSnapshot = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.RevertToCurrentSnapshot_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.SendNMI = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.SetCustomValue = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.SetDisplayTopology = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.SetScreenResolution = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.ShutdownGuest = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StandbyGuest = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StartRecording = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StartRecording_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StartReplaying = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StartReplaying_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StopRecording = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StopRecording_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StopReplaying = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.StopReplaying_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c125e0>
obj.Suspend = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.SuspendVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.Terminate = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.TerminateFaultTolerantVM = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.TerminateFaultTolerantVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.TerminateVM = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12430>
obj.TurnOffFaultTolerance = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12430>
obj.TurnOffFaultToleranceForVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12430>
obj.UnmountToolsInstaller = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12430>
obj.Unregister = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.UnregisterVM = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.UpgradeTools = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.UpgradeTools_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.UpgradeVM_Task = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj.UpgradeVirtualHardware = <function Curry.__get__.<locals>.<lambda> at 0x7fe245c12ca0>
obj._GetMethodInfo = <bound method ManagedObject._GetMethodInfo of <class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>>
obj._GetMethodList = <bound method ManagedObject._GetMethodList of <class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>>
obj._GetMoId = <bound method ManagedObject._GetMoId of 'vim.VirtualMachine:vm-333322'>
obj._GetPropertyInfo = <bound method GetPropertyInfo of <class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>>
obj._GetPropertyList = <bound method ManagedObject._GetPropertyList of <class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>>
obj._GetServerGuid = <bound method ManagedObject._GetServerGuid of 'vim.VirtualMachine:vm-333322'>
obj._GetStub = <bound method ManagedObject._GetStub of 'vim.VirtualMachine:vm-333322'>
obj._InvokeAccessor = <function ManagedObject._InvokeAccessor at 0x7fe2470794c0>
obj._InvokeMethod = <function ManagedObject._InvokeMethod at 0x7fe247079430>
obj.__class__ = <class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>
obj.__delattr__ = <bound method ManagedObject.__setattr__ of 'vim.VirtualMachine:vm-333322'>
obj.__dict__ = {'_moId': 'vm-333322', '_stub': <pyVmomi.SoapAdapter.SoapStubAdapter object at 0x7fe246992ac0>, '_serverGuid': None}
obj.__dir__ = <built-in method __dir__ of vim.VirtualMachine object at 0x7fe245e49700>
obj.__doc__ = None
obj.__eq__ = <bound method ManagedObject.__eq__ of 'vim.VirtualMachine:vm-333322'>
obj.__format__ = <built-in method __format__ of vim.VirtualMachine object at 0x7fe245e49700>
obj.__ge__ = <method-wrapper '__ge__' of vim.VirtualMachine object at 0x7fe245e49700>
obj.__getattribute__ = <method-wrapper '__getattribute__' of vim.VirtualMachine object at 0x7fe245e49700>
obj.__gt__ = <method-wrapper '__gt__' of vim.VirtualMachine object at 0x7fe245e49700>
obj.__hash__ = <bound method ManagedObject.__hash__ of 'vim.VirtualMachine:vm-333322'>
obj.__init__ = <bound method ManagedObject.__init__ of 'vim.VirtualMachine:vm-333322'>
obj.__init_subclass__ = <built-in method __init_subclass__ of LazyType object at 0x55b20e2a23b0>
obj.__le__ = <method-wrapper '__le__' of vim.VirtualMachine object at 0x7fe245e49700>
obj.__lt__ = <method-wrapper '__lt__' of vim.VirtualMachine object at 0x7fe245e49700>
obj.__module__ = pyVmomi.VmomiSupport
obj.__ne__ = <bound method ManagedObject.__ne__ of 'vim.VirtualMachine:vm-333322'>
obj.__new__ = <built-in method __new__ of type object at 0x7fe24dafe2e0>
obj.__reduce__ = <built-in method __reduce__ of vim.VirtualMachine object at 0x7fe245e49700>
obj.__reduce_ex__ = <built-in method __reduce_ex__ of vim.VirtualMachine object at 0x7fe245e49700>
obj.__repr__ = <bound method FormatObject of 'vim.VirtualMachine:vm-333322'>
obj.__setattr__ = <bound method ManagedObject.__setattr__ of 'vim.VirtualMachine:vm-333322'>
obj.__sizeof__ = <built-in method __sizeof__ of vim.VirtualMachine object at 0x7fe245e49700>
obj.__str__ = <bound method FormatObject of 'vim.VirtualMachine:vm-333322'>
obj.__subclasshook__ = <built-in method __subclasshook__ of LazyType object at 0x55b20e2a23b0>
obj.__weakref__ = None
obj._methodInfo = {'RefreshStorageInfo': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462552b0>, 'CreateSnapshot': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255370>, 'CreateSnapshotEx': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462554f0>, 'RevertToCurrentSnapshot': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255670>, 'RemoveAllSnapshots': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462557f0>, 'ConsolidateDisks': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462558b0>, 'EstimateStorageRequirementForConsolidate': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255970>, 'Reconfigure': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255a90>, 'UpgradeVirtualHardware': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255bb0>, 'ExtractOvfEnvironment': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255c70>, 'PowerOn': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255d90>, 'PowerOff': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255e50>, 'Suspend': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255f10>, 'Reset': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246255fd0>, 'ShutdownGuest': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462580d0>, 'RebootGuest': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258190>, 'StandbyGuest': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258250>, 'Answer': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258310>, 'Customize': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258490>, 'CheckCustomizationSpec': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462585b0>, 'Migrate': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258670>, 'Relocate': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462587f0>, 'Clone': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258910>, 'InstantClone': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258ac0>, 'ExportVm': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258b80>, 'MarkAsTemplate': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258c40>, 'MarkAsVirtualMachine': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258d00>, 'Unregister': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258e20>, 'ResetGuestInformation': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258ee0>, 'MountToolsInstaller': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246258fa0>, 'UnmountToolsInstaller': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b0a0>, 'UpgradeTools': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b1c0>, 'AcquireMksTicket': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b280>, 'AcquireTicket': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b3a0>, 'SetScreenResolution': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b460>, 'DefragmentAllDisks': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b580>, 'CreateSecondary': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b6a0>, 'CreateSecondaryEx': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b760>, 'TurnOffFaultTolerance': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b880>, 'MakePrimary': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625b9a0>, 'TerminateFaultTolerantVM': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625bac0>, 'DisableSecondary': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625bbe0>, 'EnableSecondary': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625bca0>, 'SetDisplayTopology': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625be20>, 'StartRecording': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625bee0>, 'StopRecording': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d040>, 'StartReplaying': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d160>, 'StopReplaying': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d220>, 'PromoteDisks': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d2e0>, 'CreateScreenshot': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d400>, 'PutUsbScanCodes': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d520>, 'QueryChangedDiskAreas': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d5e0>, 'QueryUnownedFiles': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d760>, 'ReloadFromPath': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d880>, 'QueryFaultToleranceCompatibility': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625d940>, 'QueryFaultToleranceCompatibilityEx': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625da60>, 'Terminate': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625db20>, 'SendNMI': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625dbe0>, 'AttachDisk': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625dca0>, 'DetachDisk': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625de80>, 'ApplyEvcMode': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe24625df40>, 'CryptoUnlock': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462600a0>}
obj._moId = vm-333322
obj._propInfo = {'capability': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462525b0>, 'config': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462525e0>, 'layout': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252610>, 'layoutEx': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252640>, 'storage': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252670>, 'environmentBrowser': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462526a0>, 'resourcePool': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462526d0>, 'parentVApp': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252700>, 'resourceConfig': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252730>, 'runtime': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252760>, 'guest': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252790>, 'summary': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462527c0>, 'datastore': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462527f0>, 'network': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252820>, 'snapshot': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252850>, 'rootSnapshot': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252880>, 'guestHeartbeatStatus': <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462528b0>}
obj._propList = [<pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462525b0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462525e0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252610>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252640>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252670>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462526a0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462526d0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252700>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252730>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252760>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252790>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462527c0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462527f0>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252820>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252850>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe246252880>, <pyVmomi.VmomiSupport.LazyObject object at 0x7fe2462528b0>]
obj._serverGuid = None
obj._stub = <pyVmomi.SoapAdapter.SoapStubAdapter object at 0x7fe246992ac0>
obj._version = vim.version.version1
obj._wsdlName = VirtualMachine
```

**Comment by bb-Ricardo** [comment]
I'm afraid this is not it.

It must be exactly after this line:
```
DEBUG2: Sending POST to 'http://netbox.example.com:80/api/ipam/ip-addresses/' with data 'b'{"address": "10.254.125.16/24", "assigned_object_type": "virtualization.vminterface", "dns_name": "server1.example.com"}''.
```
this is happening much later.

just output the the data to a file and grep in there to find the correct lines.

**Comment by pisaniej** [comment]
okay, hopefully this helps:

```
header: Date: Tue, 01 Feb 2022 21:39:16 GMT
header: Content-Type: application/json
header: Content-Length: 52
header: Connection: keep-alive
header: Vary: Accept, Cookie, Origin
header: Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
header: X-Content-Type-Options: nosniff
header: Referrer-Policy: same-origin
header: X-Frame-Options: SAMEORIGIN
{'count': 0, 'next': None, 'previous': None, 'results': []}
{'_body_position': None,
 '_cookies': <RequestsCookieJar[]>,
 'body': b'{"address": "0.0.0.0/24", "assigned_object_type": "virtualiza'
         b'tion.vminterface", "dns_name": "server1.example.com"}',
 'headers': {'User-Agent': 'netbox-sync/1.2.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Token xxxxxx', 'Content-Type': 'application/json', 'Content-Length': '123'},
 'hooks': {'response': []},
 'method': 'POST',
 'url': 'http://netbox.example.com:80/api/ipam/ip-addresses/'}
send: b'POST /api/ipam/ip-addresses/ HTTP/1.1\r\nHost: netbox.example.com\r\nUser-Agent: netbox-sync/1.2.2\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Token xxxxxx\r\nContent-Type: application/json\r\nContent-Length: 123\r\n\r\n'
send: b'{"address": "0.0.0.0/24", "assigned_object_type": "virtualization.vminterface", "dns_name": "server1.example.com"}'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Server: nginx/1.14.1
header: Date: Tue, 01 Feb 2022 21:39:16 GMT
header: Content-Type: text/html
header: Content-Length: 185
header: Connection: keep-alive
header: Location: https://netbox.example.com/api/ipam/ip-addresses/
send: b'GET /api/ipam/ip-addresses/ HTTP/1.1\r\nHost: netbox.example.com\r\nUser-Agent: netbox-sync/1.2.2\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Token xxxxxx\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.14.1
header: Date: Tue, 01 Feb 2022 21:39:16 GMT
header: Content-Type: application/json
header: Content-Length: 52
header: Connection: keep-alive
header: Vary: Accept, Cookie, Origin
header: Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
header: X-Content-Type-Options: nosniff
header: Referrer-Policy: same-origin
header: X-Frame-Options: SAMEORIGIN2022-02-01 16:39:16,381 - DEBUG: https://netbox.example.com:443 "GET /api/ipam/ip-addresses/ HTTP/1.1" 200 52
2022-02-01 16:39:16,382 - DEBUG2: Received HTTP Status 200.
2022-02-01 16:39:16,382 - DEBUG: Response Body:
2022-02-01 16:39:16,382 - ERROR: This 'IP address' data structure does not contain the primary key 'address' got: {'count': 0, 'next': None, 'previous': None, 'results': []}
2022-02-01 16:39:16,382 - DEBUG2: Adding unresolved dependencies back to object: ['tags', 'assigned_object_id']
2022-02-01 16:39:16,382 - DEBUG2: Parsing 'IP address' data structure: 0.0.0.0/24
```

**Comment by bb-Ricardo** [comment]
Hi,

Now I can see your issue:

you configured in your config
```ini
port = 80
disable_tls = true
```

Then hotbox-sync sends a Post request to this address:
```
send: b'POST /api/ipam/ip-addresses/ HTTP/1.1\r\nHost: netbox.example.com\r\nUser-Agent: netbox-sync/1.2.2\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Token xxxxxx\r\nContent-Type: application/json\r\nContent-Length: 123\r\n\r\n'
```

The answer is a HTTP 301 (HTTPS redirect):
```
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Location: https://netbox.example.com/api/ipam/ip-addresses/
```

According to the HTTP standard netbox-sync issues a GET request to the new location (https://softwareengineering.stackexchange.com/a/99966):
```
send: b'GET /api/ipam/ip-addresses/ HTTP/1.1\r\nHost: netbox.example.com\r\nUser-Agent: netbox-sync/1.2.2\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Token xxxxxx\r\n\r\n'
```

It seems that the HTTPS connection works just fine. Just change your config according to this and then it should work:
```ini
[netbox]
api_token = secret
host_fqdn = netbox.example.com
# port = 80
# disable_tls = true
validate_tls_certs = false
prune_enabled = false
```

Hope this helps

**Comment by pisaniej** [comment]
@bb-Ricardo that did the trick! Wow that's awesome. Thank you so much for your help.

... looks like someone incorrectly installed the cert, whoops.

**Comment by bb-Ricardo** [comment]
No problem, you're welcome 😄
