### ISSUE TITLE
VM creation error Netbox v3.3.0

### ISSUE THREAD

**Issue by yaiqsa** [bb-Ricardo/netbox-sync#220]
Hey there,

I have some issues that I guess are caused by the Netbox v3.3.0 update:

When running netbox-sync on a new database, I get the following errors:
- First this one, about a site mismatch (I think the site field is just missing)
  ```
  2022-08-22 14:41:12,771 - INFO: Creating new NetBox 'virtual machine' object 'my-hostname' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname', 'cluster': 1,
   'status': 'active', 'memory': 8192, 'vcpus': 4, 'disk': 140, 'platform': 2, 'role': 2}
  2022-08-22 14:41:12,771 - DEBUG2: Sending POST to 'https://netbox.url/api/virtualization/virtual-machines/' with data 'b'{"tags": [{"name": "NetBox-synced"}, {"name": "Source: vcenter"
  }], "name": "my-hostname", "cluster": 1, "status": "active", "memory": 8192, "vcpus": 4, "disk": 140, "platform": 2, "role": 2}''.
  2022-08-22 14:41:12,804 - DEBUG2: Received HTTP Status 400.
  2022-08-22 14:41:12,804 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
  2022-08-22 14:41:12,804 - ERROR: NetBox returned body: {'cluster': ['The selected cluster (my-cluster is not assigned to this site (None).']}
  2022-08-22 14:41:12,805 - ERROR: Request Failed for virtual machine. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname', 'cluster': 1, 'status': 'active', 'memory': 8192, 'vcpus': 4, 'disk': 140, 'platform': 2, 'role': 2}
  2022-08-22 14:41:12,805 - DEBUG2: Adding unresolved dependencies back to object: ['primary_ip4']
  2022-08-22 14:41:12,805 - DEBUG2: Parsing 'virtual machine' data structure: my-hostname
  ```
- Then this one, which I think is caused by the VM not being created:
  ```
  2022-08-22 14:41:22,441 - INFO: Creating new NetBox 'virtual machine interface' object 'vNIC 1 (Network) (my-hostname)' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'vNIC 1 (Network)', 'mac_address': '10:00:00:00:00:01', 'description': 'Network adapter 1 (VirtualE1000e) (vlan ID: 0)', 'enabled': True, 'mtu': 9000, 'mode': 'access'}
  2022-08-22 14:41:22,441 - DEBUG2: Sending POST to 'https://netbox.url/api/virtualization/interfaces/' with data 'b'{"tags": [{"name": "NetBox-synced"}, {"name": "Source: vcenter"}], "name": "vNIC 1 (Network)", "mac_address": "10:00:00:00:00:01", "description": "Network adapter 1 (VirtualE1000e) (vlan ID: 0)", "enabled": true, "mtu": 9000, "mode": "access"}''.
  2022-08-22 14:41:22,469 - DEBUG2: Received HTTP Status 400.
  2022-08-22 14:41:22,470 - ERROR: NetBox returned: POST /api/virtualization/interfaces/ Bad Request
  2022-08-22 14:41:22,470 - ERROR: NetBox returned body: {'virtual_machine': ['This field is required.']}
  2022-08-22 14:41:22,470 - ERROR: Request Failed for virtual machine interface. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'vNIC 1 (Network)', 'mac_address': '10:00:00:00:00:01', 'description': 'Network adapter 1 (VirtualE1000e) (vlan ID: 0)', 'enabled': True, 'mtu': 9000, 'mode': 'access'}
  2022-08-22 14:41:22,470 - DEBUG2: Adding unresolved dependencies back to object: ['virtual_machine']
  2022-08-22 14:41:22,471 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (Network) (my-hostname)
  ```

When I use my production database I get some more errors, but they might be caused by these objects not being created properly.

Am I correct that this is a netbox 3.3.0 compatibility issue, or is it just my environment? And if it is an incompatibility, when might this be resolved?

Thank you!

**Comment by Houtek** [comment]
There were a lo of api changes with 3.3.0 (https://github.com/netbox-community/netbox/releases/tag/v3.3.0), these might cause the issues in your environment.

**Comment by yaiqsa** [comment]
> There were a lo of api changes with 3.3.0 (https://github.com/netbox-community/netbox/releases/tag/v3.3.0), these might cause the issues in your environment.

I noticed the api changes, that's why I was wondering if netbox-sync is outdated now. (as I said, I tested with an empty (new) database, so the chance it's just my enviroment seems small)

Does netbox-sync work for anyone else using Netbox 3.3.0?

**Comment by bb-Ricardo** [comment]
Hi, I will try to have a look today and see what needs to be changed.

NetBox keeps changing APIs all the time leaving all the tools in the dust.

**Comment by bb-Ricardo** [comment]
mmhm. As I use a minikube cluster with a helm chart as my test setup I rely on provided docker images. But currently there seems to be an issue in creating new docker images for version 3.3.0

https://github.com/netbox-community/netbox-docker/issues/834

can someone perform a sync to 3.3.0 and send me the whole output? Because the API changes in 3.3.0 seem unrelated to the used attributes in netbox-sync

**Comment by t8simon** [comment]
So i got a similar issue on 3.2.7 on the development branch. But I'm not really sure if they are related or not. 
The errors start like this:  

`2022-08-25 15:14:15,132 - INFO: Creating new NetBox 'cluster' object '<cluster name>' with data: {'tags': [{'name': 'NetBo
x-synced'}, {'name': 'Source: vcenter-<vcenter>'}, {'name': 'PRD'}], 'name': '<cluster name>', 'type': 3, 'group': 8, 'site': 1,
 'tenant': 1}
2022-08-25 15:14:15,132 - DEBUG2: Sending POST to '<netbox url>/api/virtualization/clusters/' with da
ta 'b'{"tags": [{"name": "NetBox-synced"}, {"name": "Source: vcenter-<vcenter>"}, {"name": "PRD"}], "name": "<cluster name>", "t
ype": 3, "group": 8, "site": 1, "tenant": 1}''.
2022-08-25 15:14:15,170 - DEBUG2: Received HTTP Status 400.
2022-08-25 15:14:15,170 - ERROR: NetBox returned: POST /api/virtualization/clusters/ Bad Request
2022-08-25 15:14:15,171 - ERROR: NetBox returned body: {'non_field_errors': ['The fields site, name must make a unique set.']}
2022-08-25 15:14:15,171 - ERROR: Request Failed for cluster. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter-<vcenter>'}, {'name': 'PRD'}], 'name': '<cluster name>', 'type': 3, 'group': 8, 'site': 1, 'tenant': 1}`

And here is the equivalent vm creation error - but it's not exactly the same: 
`2022-08-25 15:22:09,002 - DEBUG2: Parsing 'virtual machine' data structure: <vm name>
2022-08-25 15:22:09,002 - INFO: Creating new NetBox 'virtual machine' object '<vm name>' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter-<vcenter>'}], 'name': '<vm name>', 'status': 'active', 'memory': 8192, 'vcpus': 1, 'disk': 20, 'platform': 10, 'comments': 'OS: rhel7_64Guest', 'tenant': 5, 'role': 12, 'primary_ip4': 96}
2022-08-25 15:22:09,003 - DEBUG2: Sending POST to '<url>/api/virtualization/virtual-machines/' with data 'b'{"tags": [{"name": "NetBox-synced"}, {"name": "Source: vcenter-<cluster>"}], "name": "<vm name>", "status": "active", "memory": 8192, "vcpus": 1, "disk": 20, "platform": 10, "comments": "OS: rhel7_64Guest", "tenant": 5, "role": 12, "primary_ip4": 96}''.
2022-08-25 15:22:09,044 - DEBUG2: Received HTTP Status 400.
2022-08-25 15:22:09,044 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
2022-08-25 15:22:09,044 - ERROR: NetBox returned body: {'cluster': ['This field is required.']}
2022-08-25 15:22:09,044 - ERROR: Request Failed for virtual machine. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter-<cluster>'}], 'name': '<vm name>', 'status': 'active', 'memory': 8192, 'vcpus': 1, 'disk': 20, 'platform': 10, 'comments': 'OS: rhel7_64Guest', 'tenant': 5, 'role': 12, 'primary_ip4': 96}
2022-08-25 15:22:09,045 - DEBUG2: Adding unresolved dependencies back to object: ['cluster']`


What I also found, is that the following part is missing during the VM data collection: 
`DEBUG2: Parsing 'cluster' data structure: <cluster name>`

This is at the earlier "Parsing 'virtual machine' data structure" part. In development, this part is missing. 

As a comparison, in the main branch the vm creation post looks like this: 
`2022-08-25 16:08:51,939 - INFO: Creating new NetBox 'virtual machine' object '<vm name>' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter-<vcenter>'}], 'name': '<vm name>', 'cluster': 7, 'status': 'active', 'memory': 8192, 'vcpus': 2, 'disk': 40, 'platform': 10, 'comments': 'OS: rhel7_64Guest', 'tenant': 19, 'role': 12}`

So it seems in the development branch the cluster ID is not pushed during vm creation. Maybe this is because of the error before, where it wants to create clusters that already exists?

**Comment by bb-Ricardo** [comment]
I changed some code around the cluster creation. Somehow it doesn't seem to pick up the existing cluster and then everything goes to sh*t. Can you have a look at the updated config example file about the cluster site relation?

I added support for clusters with the same name but in different datacenters. And it could be caused by this change.

**Comment by t8simon** [comment]
So I have only unique cluster names, everything is defined like this: `Cluster_NYC = New York`. 
But the clusters already do exist in netbox before the sync (which is no issue with main branch, but for the code on development it is).

**Comment by bb-Ricardo** [comment]
Then I will try to figure it out tonight.

**Comment by bb-Ricardo** [comment]
Hi @t8simon, I just tested it and it seems I at least found your issue. the script indeed tries to create a new cluster  because the cluster group (Datacenter) is now part of the identifier to make this cluster unique. Lets how I can fix this.

**Comment by bb-Ricardo** [comment]
Hello @yaiqsa, @t8simon,

I just pushed a fix for the issue. Can you try latest `development` branch please and let me know if it's working? Preferably with 3.2 and 3.3 version if possible.

Thank you very much.

**Comment by t8simon** [comment]
No luck yet unfortunately, the error seems to be still the same: 

```
2022-08-25 22:11:46,176 - INFO: Creating new NetBox 'cluster' object '<cluster name>' with data: {'tags': [{'name': 'NetBo
x-synced'}, {'name': 'Source: vcenter-<vcenter>'}, {'name': 'PRD'}], 'name': '<cluster name>', 'type': 3, 'group': 8, 'site': 1,
 'tenant': 1}
2022-08-25 22:11:46,177 - DEBUG2: Sending POST to '<url>/api/virtualization/clusters/' with data 'b'{"tags": [{"name": "NetBox-synced"}, {"name": "Source: vcenter-<vcenter>"}, {"name": "PRD"}], "name": "<cluster name>", "type": 3, "group": 8, "site": 1, "tenant": 1}''.
2022-08-25 22:11:46,214 - DEBUG2: Received HTTP Status 400.
2022-08-25 22:11:46,214 - ERROR: NetBox returned: POST /api/virtualization/clusters/ Bad Request
2022-08-25 22:11:46,215 - ERROR: NetBox returned body: {'non_field_errors': ['The fields site, name must make a unique set.']}
2022-08-25 22:11:46,215 - ERROR: Request Failed for cluster. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter-<vcenter>'}, {'name': 'PRD'}], 'name': '<cluster name>', 'type': 3, 'group': 8, 'site': 1, 'tenant': 1}
```

**Comment by bb-Ricardo** [comment]
Hey @t8simon, would you mind sending me the whole log and also the api output of the cluster id 1 to my email (command option -h)? This is very strange.

**Comment by t8simon** [comment]
I'm probably not allowed to do this. This error is btw not just for ID 1, but for all clusters. 
The clusters already do exist in netbox with those names (as I was documenting all the HW beforehand). 

We can have a chat in the netbox slack if you want. You find me with the same username there.

**Comment by bb-Ricardo** [comment]
Hi @yaiqsa,

Can you check out the latest `development` branch and see if this issue is fixed for you. Thanks to @t8simon we could narrow down the issue and finally solve it.

**Comment by bb-Ricardo** [comment]
Unfortunately not. Still no updated docker images.

If anyone could test it against current main, that would be great.

**Comment by SerhiiZahuba** [comment]
1) 
After the update, I see errors in the log
Such error for each server.
`2022-08-29 11:42:11,236 - DEBUG: Parsing vCenter host: 192.168.50.150
2022-08-29 11:42:11,620 - ERROR: Requesting cluster for host '192.168.50.150' failed. Skipping.
2022-08-29 11:42:11,696 - DEBUG: Parsing vCenter host: 192.168.50.110
2022-08-29 11:42:12,081 - ERROR: Requesting cluster for host '192.168.50.110' failed. Skipping.
2022-08-29 11:42:12,158 - DEBUG: Parsing vCenter host: 192.168.50.180
2022-08-29 11:42:12,537 - ERROR: Requesting cluster for host '192.168.50.180' failed. Skipping.
2022-08-29 11:42:12,613 - DEBUG: Parsing vCenter host: 192.168.50.145
2022-08-29 11:42:12,994 - ERROR: Requesting cluster for host '192.168.50.145' failed. Skipping.
2022-08-29 11:42:15,440 - ERROR: Requesting cluster for host '192.168.50.200' failed. Skipping.
2022-08-29 11:42:15,517 - DEBUG: Parsing vCenter host: 192.168.50.250
2022-08-29 11:42:15,898 - ERROR: Requesting cluster for host '192.168.50.250' failed. Skipping`

2) log file is not created (I created the folder manually) but the folder is empty

3) virtual machines are not created, only IP addresses to them

**Comment by bb-Ricardo** [comment]
Hi @SerhiiZahuba,

Did you test current main against 3.3.1? Does 1.2.3 work?

please open a separat issue if it's not dependent on the NetBox version.

**Comment by SerhiiZahuba** [comment]
Yes. I'm sorry. I will make a separate issue.

**Comment by yaiqsa** [comment]
@bb-Ricardo I tested the new development version as well; (on netbox 3.3.0)
I don't get @SerhiiZahuba 's `Requesting cluster for host` errors, but I do still get the following ones:

For each VM:
```
2022-08-29 11:46:46,500 - INFO: Creating new NetBox 'virtual machine' object 'my-hostname' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname, 'cluster': 1, 'status': 'active', 'memory': 1234, 'vcpus': 2, 'disk': 100, 'platform': 2, 'role': 2}
2022-08-29 11:46:46,573 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
2022-08-29 11:46:46,574 - ERROR: NetBox returned body: {'cluster': ['The selected cluster (vmcluster is not assigned to this site (None).']}
2022-08-29 11:46:46,574 - ERROR: Request Failed for virtual machine. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname', 'cluster': 1, 'status': 'active', 'memory': 8192, 'vcpus': 4, 'disk': 100, 'platform': 2, 'role': 2}
```

And then for each interface:
```
2022-08-29 11:48:24,024 - INFO: Creating new NetBox 'virtual machine interface' object 'vNIC 1 (VM Network) (my-hostname)' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}
], 'name': 'vNIC 1 (VM Network)', 'mac_address': '00:50:56:82:A8:41', 'description': 'Network adapter 1 (VirtualVmxnet3)', 'enabled': True}
2022-08-29 11:48:24,080 - ERROR: NetBox returned: POST /api/virtualization/interfaces/ Bad Request
2022-08-29 11:48:24,081 - ERROR: NetBox returned body: {'virtual_machine': ['This field is required.']}
2022-08-29 11:48:24,081 - ERROR: Request Failed for virtual machine interface. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'vNIC 1 (VM Network)', 'mac_address'
: '00:50:56:82:A8:41', 'description': 'Network adapter 1 (VirtualVmxnet3)', 'enabled': True}
```

I'm going to test 3.3.1 now, but I don't expect a very different result, looking at the changelogs

**Comment by bb-Ricardo** [comment]
> @bb-Ricardo I tested the new development version as well; (on netbox 3.3.0) I don't get @SerhiiZahuba 's `Requesting cluster for host` errors, but I do still get the following ones:
> 
> For each VM:
> 
> ```
> 2022-08-29 11:46:46,500 - INFO: Creating new NetBox 'virtual machine' object 'my-hostname' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname, 'cluster': 1, 'status': 'active', 'memory': 1234, 'vcpus': 2, 'disk': 100, 'platform': 2, 'role': 2}
> 2022-08-29 11:46:46,573 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
> 2022-08-29 11:46:46,574 - ERROR: NetBox returned body: {'cluster': ['The selected cluster (vmcluster is not assigned to this site (None).']}
> 2022-08-29 11:46:46,574 - ERROR: Request Failed for virtual machine. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname', 'cluster': 1, 'status': 'active', 'memory': 8192, 'vcpus': 4, 'disk': 100, 'platform': 2, 'role': 2}
> ```
> 
> And then for each interface:
> 
> ```
> 2022-08-29 11:48:24,024 - INFO: Creating new NetBox 'virtual machine interface' object 'vNIC 1 (VM Network) (my-hostname)' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}
> ], 'name': 'vNIC 1 (VM Network)', 'mac_address': '00:50:56:82:A8:41', 'description': 'Network adapter 1 (VirtualVmxnet3)', 'enabled': True}
> 2022-08-29 11:48:24,080 - ERROR: NetBox returned: POST /api/virtualization/interfaces/ Bad Request
> 2022-08-29 11:48:24,081 - ERROR: NetBox returned body: {'virtual_machine': ['This field is required.']}
> 2022-08-29 11:48:24,081 - ERROR: Request Failed for virtual machine interface. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'vNIC 1 (VM Network)', 'mac_address'
> : '00:50:56:82:A8:41', 'description': 'Network adapter 1 (VirtualVmxnet3)', 'enabled': True}
> ```
> 
> I'm going to test 3.3.1 now, but I don't expect a very different result, looking at the changelogs

And it works without issues and the same data on a NetBox 3.2.9??

**Comment by bb-Ricardo** [comment]
@yaiqsa, did you check if the option `site_cluster_relation` is set correctly?
can you use the option `-l DEBUG2` and paste the output of the cluster parsing? It should be right before the venter networks.

Thank you.

**Comment by yaiqsa** [comment]
> And it works without issues and the same data on a NetBox 3.2.9??

Correct, NetBox 3.2.9 runs fine.
(It took a little while because it seems it's not possible to downgrade netbox.. so now I run two instances 😅 )

On NetBox 3.3.1 I get the same errors as on 3.3.0

**Comment by yaiqsa** [comment]
> @yaiqsa, did you check if the option `site_cluster_relation` is set correctly? can you use the option `-l DEBUG2` and paste the output of the cluster parsing? It should be right before the venter networks.
> 
> Thank you.

cluster_site_relation seems to be set correctly ( I guess otherwise 3.2.9 wouldn't work either?)

And I think you mean this part?:
```
2022-08-29 13:32:18,229 - DEBUG: Parsing vCenter datacenter: DATACENTER
2022-08-29 13:32:18,229 - DEBUG2: Parsing 'cluster group' data structure: DATACENTER
2022-08-29 13:32:18,259 - DEBUG: vCenter returned '1' cluster
2022-08-29 13:32:18,281 - DEBUG: Parsing vCenter cluster: DATACENTER/vmcluster
2022-08-29 13:32:18,282 - DEBUG2: Trying to find site name for cluster 'DATACENTER/vmcluster'
2022-08-29 13:32:18,282 - DEBUG2: Found a matching cluster_site_relation 'Colo DATACENTER' (vmcluster) for vmcluster
2022-08-29 13:32:18,282 - DEBUG2: Trying to find a matching existing cluster
2022-08-29 13:32:18,282 - DEBUG2: Found an existing cluster where 'name' and 'site' are matching
2022-08-29 13:32:18,282 - DEBUG2: Parsing 'cluster' data structure: vmcluster
2022-08-29 13:32:18,283 - DEBUG2: Parsing 'cluster type' data structure: VMware ESXi
```

**Comment by bb-Ricardo** [comment]
Thank you for your patient and time testing.

somehow the error `{'cluster': ['The selected cluster (vmcluster is not assigned to this site (None).']}` seems to me to be an error in NetBox itself. it should not state `None` as site name.

**Comment by yaiqsa** [comment]
> Thank you for your patient and time testing.
> 
> somehow the error `{'cluster': ['The selected cluster (vmcluster is not assigned to this site (None).']}` seems to me to be an error in NetBox itself. it should not state `None` as site name.

You're right, I think? When I create a new VM in the webinterface, and just set the name, and cluster (without setting the site), I also get an `The selected cluster (ams-vmcluster-01 is not assigned to this site (None). ` error!

Despite that, I think this would be fixed if the script would pass the right site in the API call, but this might also be something that NetBox could (should?) fix

**Comment by bb-Ricardo** [comment]
Ahh, interesting.
also this line
`2022-08-29 11:46:46,500 - INFO: Creating new NetBox 'virtual machine' object 'my-hostname' with data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: vcenter'}], 'name': 'my-hostname, 'cluster': 1, 'status': 'active', 'memory': 1234, 'vcpus': 2, 'disk': 100, 'platform': 2, 'role': 2}
`
includes the cluster ID "1".
So that means that the site is missing during the cluster creation. Can you check the logs for the  entries creating the clusters?

Thank you

**Comment by yaiqsa** [comment]
By

> > Thank you for your patient and time testing.
> > somehow the error `{'cluster': ['The selected cluster (vmcluster is not assigned to this site (None).']}` seems to me to be an error in NetBox itself. it should not state `None` as site name.
> 
> You're right, I think? When I create a new VM in the webinterface, and just set the name, and cluster (without setting the site), I also get an `The selected cluster (ams-vmcluster-01 is not assigned to this site (None). ` error!
> 
> Despite that, I think this would be fixed if the script would pass the right site in the API call, but this might also be something that NetBox could (should?) fix

By the way; I think this is expected behavior, not a bug.. (https://github.com/netbox-community/netbox/issues/10131#issuecomment-1225783758)

**Comment by yaiqsa** [comment]
> So we need to set the site attribute as well even though it is defined by the cluster this VM belongs to? Do I get this right?

Yes, it appears so.

>If the site is enforced by the cluster, then why do I need to set it?

Not a clue.. And we're not the only one having problems with this [this issue](https://github.com/netbox-community/netbox/issues/10088) regards the same problem..


And I see you already read [jeremystretch](https://github.com/jeremystretch)'s response:
> You've skipped the part where you create the cluster. If the cluster to which you're assigning the VM is associated with a site, then this is expected: Both the VM and its cluster must belong to the same site, or to no site.

**Comment by bb-Ricardo** [comment]
I just tested this in the NetBox demo. This is a bug. Because if I select a cluster, then site becomes a mandatory field with only one possible option. This is very strange.

**Comment by yaiqsa** [comment]
> I just tested this in the NetBox demo. This is a bug. Because if I select a cluster, then site becomes a mandatory field with only one possible option. This is very strange.

I agree.

From my point of view we can wait a few days to see if this will get patched, or if they keep they keep their current opinion.
If that's the case I'd suggest patching it anyway.. I wouldn't start a NetBox fork over this 😉 

If you don't have the time for that patch I can take a look at it sometime soon.

**Comment by bb-Ricardo** [comment]
If this is by design and persists then I need to add a validation on the NetBox version and add the site attribute conditionally. like to avoid that, but the NetBox people are sometimes hard to argue with. But understandable in such a big project.

**Comment by yaiqsa** [comment]
> If this is by design and persists then I need to add a validation on the NetBox version and add the site attribute conditionally. like to avoid that, but the NetBox people are sometimes hard to argue with. But understandable in such a big project.

Ah, that's true. Yeah, they do amazing work, but also understand your perspective on it.
We'll see how this turns out.
(In the meantime, thank you for picking this issue up, and making the project in the first place, its very useful!)

**Comment by bb-Ricardo** [comment]
Hi @yaiqsa,

I just pushed another commit to the `development` branch. Can you give it a try to see if VM creation works now?

Thank you very much.

**Comment by yaiqsa** [comment]
> Hi @yaiqsa,
> 
> I just pushed another commit to the `development` branch. Can you give it a try to see if VM creation works now?
> 
> Thank you very much.

Oh, sorry for the late reply. Life happened.

The patch seems to work! On a fresh database I get a successful sync without any errors (and the resulting data also seems correct)

In my production environment everything seems to work fine as well. (I do get some errors, but they are regarding a different, more niche problem)

So I think we can close this issue? Thanks for the patch!

**Comment by bb-Ricardo** [comment]
Thank you for testing the fix, will close this issue
